<?php

namespace Database\Seeders;

use App\Models\Juego;
use Illuminate\Database\Seeder;

class CatalogoAmpliadoSeeder extends Seeder
{
    public function run(): void
    {
        $juegos = [
            [
                'nombre' => 'Resident Evil 2',
                'franquicia' => 'Resident Evil',
                'anio' => 1998,
                'plataformas' => 'PlayStation, Nintendo 64, Dreamcast y PC',
                'genero' => 'Survival horror',
                'desarrollador' => 'Capcom',
                'descripcion' => 'Leon S. Kennedy y Claire Redfield intentan sobrevivir al brote zombi que destruyó Raccoon City.',
                'imagen' => '/imagenes/juegos/resident-evil-2.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Resident Evil 4',
                'franquicia' => 'Resident Evil',
                'anio' => 2005,
                'plataformas' => 'GameCube, PlayStation 2, Wii y PC',
                'genero' => 'Acción y survival horror',
                'desarrollador' => 'Capcom',
                'descripcion' => 'Leon viaja a una zona rural de Europa para rescatar a la hija del presidente de Estados Unidos.',
                'imagen' => '/imagenes/juegos/resident-evil-4.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/254700/Resident_Evil_4_2005/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Resident Evil 4 Remake',
                'franquicia' => 'Resident Evil',
                'anio' => 2023,
                'plataformas' => 'PlayStation 4, PlayStation 5, Xbox Series X|S y PC',
                'genero' => 'Acción y survival horror',
                'desarrollador' => 'Capcom',
                'descripcion' => 'Nueva versión de la aventura de Leon con jugabilidad moderna, escenarios renovados y una historia ampliada.',
                'imagen' => '/imagenes/juegos/resident-evil-4-remake.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/2050650/Resident_Evil_4/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Final Fantasy VII',
                'franquicia' => 'Final Fantasy',
                'anio' => 1997,
                'plataformas' => 'PlayStation, Nintendo Switch, Xbox One y PC',
                'genero' => 'RPG por turnos',
                'desarrollador' => 'Square',
                'descripcion' => 'Cloud Strife se une al grupo Avalancha para luchar contra la corporación Shinra y enfrentar a Sephiroth.',
                'imagen' => '/imagenes/juegos/final-fantasy-vii.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/39140/FINAL_FANTASY_VII/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Final Fantasy VII Remake',
                'franquicia' => 'Final Fantasy',
                'anio' => 2020,
                'plataformas' => 'PlayStation 4, PlayStation 5 y PC',
                'genero' => 'Acción RPG',
                'desarrollador' => 'Square Enix',
                'descripcion' => 'Reinterpretación de la historia de Midgar con combates en tiempo real y elementos estratégicos.',
                'imagen' => '/imagenes/juegos/final-fantasy-vii-remake.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/1462040/FINAL_FANTASY_VII_REMAKE_INTERGRADE/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Final Fantasy X',
                'franquicia' => 'Final Fantasy',
                'anio' => 2001,
                'plataformas' => 'PlayStation 2, PlayStation 4, Xbox One, Nintendo Switch y PC',
                'genero' => 'RPG por turnos',
                'desarrollador' => 'Square',
                'descripcion' => 'Tidus llega al mundo de Spira y acompaña a Yuna durante su peregrinación para derrotar a Sinh.',
                'imagen' => '/imagenes/juegos/final-fantasy-x.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/359870/FINAL_FANTASY_XX2_HD_Remaster/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'God of War',
                'franquicia' => 'God of War',
                'anio' => 2005,
                'plataformas' => 'PlayStation 2 y PlayStation 3',
                'genero' => 'Acción y aventura',
                'desarrollador' => 'Santa Monica Studio',
                'descripcion' => 'Kratos inicia su violenta lucha contra Ares y los dioses de la mitología griega.',
                'imagen' => '/imagenes/juegos/god-of-war-2005.jpg',
                'estado_disponibilidad' => 'Solo formato físico',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'God of War Ragnarök',
                'franquicia' => 'God of War',
                'anio' => 2022,
                'plataformas' => 'PlayStation 4, PlayStation 5 y PC',
                'genero' => 'Acción y aventura',
                'desarrollador' => 'Santa Monica Studio',
                'descripcion' => 'Kratos y Atreus recorren los nueve reinos mientras se preparan para la llegada del Ragnarök.',
                'imagen' => '/imagenes/juegos/god-of-war-ragnarok.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/2322010/God_of_War_Ragnark/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'The Last of Us',
                'franquicia' => 'The Last of Us',
                'anio' => 2013,
                'plataformas' => 'PlayStation 3',
                'genero' => 'Acción, aventura y supervivencia',
                'desarrollador' => 'Naughty Dog',
                'descripcion' => 'Joel debe acompañar a Ellie a través de unos Estados Unidos destruidos por una infección.',
                'imagen' => '/imagenes/juegos/the-last-of-us.jpg',
                'estado_disponibilidad' => 'Solo formato físico',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'The Legend of Zelda: Ocarina of Time',
                'franquicia' => 'The Legend of Zelda',
                'anio' => 1998,
                'plataformas' => 'Nintendo 64, Nintendo 3DS y Nintendo Switch',
                'genero' => 'Acción y aventura',
                'desarrollador' => 'Nintendo',
                'descripcion' => 'Link viaja a través del tiempo para impedir que Ganondorf conquiste el reino de Hyrule.',
                'imagen' => '/imagenes/juegos/zelda-ocarina-of-time.jpg',
                'estado_disponibilidad' => 'Disponible con suscripción',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'The Legend of Zelda: Breath of the Wild',
                'franquicia' => 'The Legend of Zelda',
                'anio' => 2017,
                'plataformas' => 'Wii U y Nintendo Switch',
                'genero' => 'Acción, aventura y mundo abierto',
                'desarrollador' => 'Nintendo',
                'descripcion' => 'Link despierta después de cien años y explora libremente Hyrule para recuperar sus recuerdos.',
                'imagen' => '/imagenes/juegos/zelda-breath-of-the-wild.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Super Mario 64',
                'franquicia' => 'Super Mario',
                'anio' => 1996,
                'plataformas' => 'Nintendo 64 y Nintendo Switch',
                'genero' => 'Plataformas 3D',
                'desarrollador' => 'Nintendo',
                'descripcion' => 'Mario explora las pinturas del castillo de Peach para recuperar las estrellas robadas por Bowser.',
                'imagen' => '/imagenes/juegos/super-mario-64.jpg',
                'estado_disponibilidad' => 'Disponible con suscripción',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Super Mario Odyssey',
                'franquicia' => 'Super Mario',
                'anio' => 2017,
                'plataformas' => 'Nintendo Switch',
                'genero' => 'Plataformas 3D',
                'desarrollador' => 'Nintendo',
                'descripcion' => 'Mario y Cappy recorren distintos reinos para impedir el matrimonio planeado por Bowser.',
                'imagen' => '/imagenes/juegos/super-mario-odyssey.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Sonic Adventure 2',
                'franquicia' => 'Sonic the Hedgehog',
                'anio' => 2001,
                'plataformas' => 'Dreamcast, GameCube, PlayStation 3, Xbox 360 y PC',
                'genero' => 'Plataformas y acción',
                'desarrollador' => 'Sonic Team',
                'descripcion' => 'Sonic y Shadow protagonizan dos campañas conectadas en una lucha por salvar el planeta.',
                'imagen' => '/imagenes/juegos/sonic-adventure-2.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/213610/Sonic_Adventure_2/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Halo: Combat Evolved',
                'franquicia' => 'Halo',
                'anio' => 2001,
                'plataformas' => 'Xbox y PC',
                'genero' => 'Disparos en primera persona',
                'desarrollador' => 'Bungie',
                'descripcion' => 'El Jefe Maestro lucha contra el Covenant y descubre el verdadero propósito del anillo Halo.',
                'imagen' => '/imagenes/juegos/halo-combat-evolved.jpg',
                'estado_disponibilidad' => 'Disponible en recopilación',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Gears of War',
                'franquicia' => 'Gears of War',
                'anio' => 2006,
                'plataformas' => 'Xbox 360 y PC',
                'genero' => 'Disparos en tercera persona',
                'desarrollador' => 'Epic Games',
                'descripcion' => 'Marcus Fenix y el escuadrón Delta combaten a la Horda Locust utilizando un sistema de cobertura.',
                'imagen' => '/imagenes/juegos/gears-of-war.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Grand Theft Auto: San Andreas',
                'franquicia' => 'Grand Theft Auto',
                'anio' => 2004,
                'plataformas' => 'PlayStation 2, Xbox y PC',
                'genero' => 'Acción y mundo abierto',
                'desarrollador' => 'Rockstar North',
                'descripcion' => 'Carl Johnson regresa a Los Santos y se involucra nuevamente con su familia y su antigua pandilla.',
                'imagen' => '/imagenes/juegos/gta-san-andreas.jpg',
                'estado_disponibilidad' => 'Disponible en edición remasterizada',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Grand Theft Auto V',
                'franquicia' => 'Grand Theft Auto',
                'anio' => 2013,
                'plataformas' => 'PlayStation 3, PlayStation 4, PlayStation 5, Xbox y PC',
                'genero' => 'Acción y mundo abierto',
                'desarrollador' => 'Rockstar North',
                'descripcion' => 'Michael, Franklin y Trevor realizan peligrosos golpes criminales en la ciudad de Los Santos.',
                'imagen' => '/imagenes/juegos/gta-v.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/3240220/Grand_Theft_Auto_V_Enhanced/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Red Dead Redemption 2',
                'franquicia' => 'Red Dead Redemption',
                'anio' => 2018,
                'plataformas' => 'PlayStation 4, Xbox One y PC',
                'genero' => 'Acción, aventura y mundo abierto',
                'desarrollador' => 'Rockstar Games',
                'descripcion' => 'Arthur Morgan y la banda de Dutch intentan sobrevivir durante los últimos años del Salvaje Oeste.',
                'imagen' => '/imagenes/juegos/red-dead-redemption-2.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Dark Souls',
                'franquicia' => 'Dark Souls',
                'anio' => 2011,
                'plataformas' => 'PlayStation 3, Xbox 360 y PC',
                'genero' => 'Acción RPG',
                'desarrollador' => 'FromSoftware',
                'descripcion' => 'Un no muerto recorre el reino de Lordran, enfrentando enemigos exigentes y descubriendo su historia.',
                'imagen' => '/imagenes/juegos/dark-souls.jpg',
                'estado_disponibilidad' => 'Disponible en edición remasterizada',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Elden Ring',
                'franquicia' => 'Elden Ring',
                'anio' => 2022,
                'plataformas' => 'PlayStation 4, PlayStation 5, Xbox One, Xbox Series X|S y PC',
                'genero' => 'Acción RPG y mundo abierto',
                'desarrollador' => 'FromSoftware',
                'descripcion' => 'Un Sinluz explora las Tierras Intermedias para reunir las grandes runas y convertirse en señor.',
                'imagen' => '/imagenes/juegos/elden-ring.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/1245620/ELDEN_RING/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Call of Duty 4: Modern Warfare',
                'franquicia' => 'Call of Duty',
                'anio' => 2007,
                'plataformas' => 'PlayStation 3, Xbox 360, Wii y PC',
                'genero' => 'Disparos en primera persona',
                'desarrollador' => 'Infinity Ward',
                'descripcion' => 'Una campaña militar moderna alterna las operaciones de soldados estadounidenses y británicos.',
                'imagen' => '/imagenes/juegos/call-of-duty-4.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/7940/Call_of_Duty_4_Modern_Warfare_2007/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Minecraft',
                'franquicia' => 'Minecraft',
                'anio' => 2011,
                'plataformas' => 'PlayStation, Xbox, Nintendo Switch, dispositivos móviles y PC',
                'genero' => 'Supervivencia y construcción',
                'desarrollador' => 'Mojang Studios',
                'descripcion' => 'Un mundo construido con bloques permite explorar, reunir recursos, sobrevivir y crear estructuras.',
                'imagen' => '/imagenes/juegos/minecraft.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://www.minecraft.net/store/minecraft-deluxe-collection-pc',
                'texto_enlace' => 'Ver sitio oficial',
            ],
            [
                'nombre' => 'Silent Hill 2',
                'franquicia' => 'Silent Hill',
                'anio' => 2001,
                'plataformas' => 'PlayStation 2, Xbox y PC',
                'genero' => 'Terror psicológico',
                'desarrollador' => 'Team Silent',
                'descripcion' => 'James Sunderland viaja a Silent Hill después de recibir una carta de su esposa fallecida.',
                'imagen' => '/imagenes/juegos/silent-hill-2.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Tekken 5',
                'franquicia' => 'Tekken',
                'anio' => 2004,
                'plataformas' => 'Arcade y PlayStation 2',
                'genero' => 'Lucha',
                'desarrollador' => 'Namco',
                'descripcion' => 'El quinto Torneo del Rey del Puño de Hierro reúne a luchadores con diferentes historias y estilos.',
                'imagen' => '/imagenes/juegos/tekken-5.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
        ];

        foreach ($juegos as $juego) {
            Juego::updateOrCreate(
                ['nombre' => $juego['nombre']],
                $juego
            );
        }
    }
}