<?php

namespace Database\Seeders;

use App\Models\Juego;
use Illuminate\Database\Seeder;

class JuegoSeeder extends Seeder
{
    public function run(): void
    {
        $juegos = [
            [
                'nombre' => 'Digimon World',
                'franquicia' => 'Digimon',
                'anio' => 1999,
                'plataformas' => 'PlayStation',
                'genero' => 'RPG, crianza y aventura',
                'desarrollador' => 'Bandai',
                'descripcion' => 'Un joven es transportado al Mundo Digital y debe ayudar a reconstruir File City. El jugador cría a su compañero Digimon, lo alimenta, entrena y guía durante las exploraciones.',
                'imagen' => '/imagenes/juegos/digimon-world.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Digimon World 2',
                'franquicia' => 'Digimon',
                'anio' => 2000,
                'plataformas' => 'PlayStation',
                'genero' => 'RPG y exploración de mazmorras',
                'desarrollador' => 'Bandai',
                'descripcion' => 'El jugador se une a un equipo de domadores y explora dominios digitales utilizando un vehículo especial. Los combates permiten formar grupos de hasta tres Digimon.',
                'imagen' => '/imagenes/juegos/digimon-world-2.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Digimon World 3',
                'franquicia' => 'Digimon',
                'anio' => 2002,
                'plataformas' => 'PlayStation',
                'genero' => 'RPG por turnos',
                'desarrollador' => 'Bandai',
                'descripcion' => 'Un jugador queda atrapado dentro de un videojuego en línea y debe recorrer varias ciudades digitales, combatir con Digimon y descubrir una conspiración que amenaza ambos mundos.',
                'imagen' => '/imagenes/juegos/digimon-world-3.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Digimon Rumble Arena',
                'franquicia' => 'Digimon',
                'anio' => 2001,
                'plataformas' => 'PlayStation',
                'genero' => 'Lucha',
                'desarrollador' => 'Hudson Soft',
                'descripcion' => 'Videojuego de combates en escenarios cerrados donde diferentes Digimon utilizan ataques especiales y pueden evolucionar temporalmente durante las peleas.',
                'imagen' => '/imagenes/juegos/digimon-rumble-arena.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Digimon World 4',
                'franquicia' => 'Digimon',
                'anio' => 2005,
                'plataformas' => 'PlayStation 2, GameCube y Xbox',
                'genero' => 'Acción RPG',
                'desarrollador' => 'BEC',
                'descripcion' => 'Una aventura cooperativa enfocada en la acción. Los jugadores controlan directamente a sus Digimon, utilizan armas, derrotan enemigos y recorren distintas zonas digitales.',
                'imagen' => '/imagenes/juegos/digimon-world-4.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Digimon World DS',
                'franquicia' => 'Digimon',
                'anio' => 2006,
                'plataformas' => 'Nintendo DS',
                'genero' => 'RPG por turnos',
                'desarrollador' => 'Namco Bandai Games',
                'descripcion' => 'El jugador comienza como domador y debe investigar extraños sucesos en el Mundo Digital. Incluye captura mediante escaneo, entrenamiento, granjas y evolución de Digimon.',
                'imagen' => '/imagenes/juegos/digimon-world-ds.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Digimon World Dawn',
                'franquicia' => 'Digimon',
                'anio' => 2007,
                'plataformas' => 'Nintendo DS',
                'genero' => 'RPG por turnos',
                'desarrollador' => 'Namco Bandai Games',
                'descripcion' => 'Tras un extraño ataque, el jugador debe ayudar al equipo Light Fang. Incluye cientos de Digimon, misiones, crianza, fusiones y combates por turnos.',
                'imagen' => '/imagenes/juegos/digimon-world-dawn.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Digimon World Dusk',
                'franquicia' => 'Digimon',
                'anio' => 2007,
                'plataformas' => 'Nintendo DS',
                'genero' => 'RPG por turnos',
                'desarrollador' => 'Namco Bandai Games',
                'descripcion' => 'Versión complementaria de Dawn protagonizada por el equipo Night Crow. Presenta Digimon y misiones diferentes, manteniendo el sistema de crianza y combate por turnos.',
                'imagen' => '/imagenes/juegos/digimon-world-dusk.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Digimon Story: Cyber Sleuth',
                'franquicia' => 'Digimon',
                'anio' => 2015,
                'plataformas' => 'PlayStation 4 y PlayStation Vita',
                'genero' => 'RPG y misterio',
                'desarrollador' => 'Media.Vision',
                'descripcion' => 'El protagonista investiga incidentes ocurridos entre el mundo real y el ciberespacio EDEN. Permite escanear, criar, evolucionar y combatir utilizando equipos de Digimon.',
                'imagen' => '/imagenes/juegos/digimon-cyber-sleuth.jpg',
                'estado_disponibilidad' => 'Solo formato físico',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => "Digimon Story: Cyber Sleuth - Hacker's Memory",
                'franquicia' => 'Digimon',
                'anio' => 2017,
                'plataformas' => 'PlayStation 4 y PlayStation Vita',
                'genero' => 'RPG y misterio',
                'desarrollador' => 'Media.Vision',
                'descripcion' => 'La historia sigue a Keisuke Amazawa, quien se convierte en hacker para limpiar su nombre. Su aventura ocurre paralelamente a los eventos del primer Cyber Sleuth.',
                'imagen' => '/imagenes/juegos/digimon-hackers-memory.jpg',
                'estado_disponibilidad' => 'Solo formato físico',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Digimon Story Cyber Sleuth: Complete Edition',
                'franquicia' => 'Digimon',
                'anio' => 2019,
                'plataformas' => 'Nintendo Switch y PC',
                'genero' => 'RPG por turnos',
                'desarrollador' => 'Media.Vision',
                'descripcion' => 'Edición que reúne Cyber Sleuth y Hacker’s Memory. Incluye ambas historias, combates por turnos y más de 300 Digimon para coleccionar, criar y evolucionar.',
                'imagen' => '/imagenes/juegos/digimon-complete-edition.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/1042550/Digimon_Story_Cyber_Sleuth_Complete_Edition/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Digimon World: Next Order',
                'franquicia' => 'Digimon',
                'anio' => 2016,
                'plataformas' => 'PlayStation 4, Nintendo Switch y PC',
                'genero' => 'RPG, aventura y crianza',
                'desarrollador' => 'B.B. Studio',
                'descripcion' => 'El protagonista llega a un Mundo Digital en crisis y debe entrenar simultáneamente a dos compañeros Digimon, reconstruir la ciudad y combatir amenazas digitales.',
                'imagen' => '/imagenes/juegos/digimon-next-order.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/1530160/Digimon_World_Next_Order/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Digimon Survive',
                'franquicia' => 'Digimon',
                'anio' => 2022,
                'plataformas' => 'PlayStation 4, Xbox One, Nintendo Switch y PC',
                'genero' => 'Novela visual y RPG táctico',
                'desarrollador' => 'Hyde',
                'descripcion' => 'Un grupo de estudiantes queda atrapado en un mundo peligroso. Las decisiones del jugador afectan sus relaciones, evoluciones, combates y el desenlace de la historia.',
                'imagen' => '/imagenes/juegos/digimon-survive.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/871980/Digimon_Survive/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Digimon Story: Time Stranger',
                'franquicia' => 'Digimon',
                'anio' => 2025,
                'plataformas' => 'PlayStation 5, Xbox Series X|S y PC',
                'genero' => 'RPG y colección de criaturas',
                'desarrollador' => 'Media.Vision',
                'descripcion' => 'Una aventura que conecta el mundo humano y el Mundo Digital mientras el protagonista investiga un misterio relacionado con el colapso de ambos mundos.',
                'imagen' => '/imagenes/juegos/digimon-time-stranger.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/1984270/Digimon_Story_Time_Stranger/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Monster Hunter: World',
                'franquicia' => 'Monster Hunter',
                'anio' => 2018,
                'plataformas' => 'PlayStation 4, Xbox One y PC',
                'genero' => 'Acción RPG y cacería',
                'desarrollador' => 'Capcom',
                'descripcion' => 'Explora el Nuevo Mundo, estudia monstruos gigantes y fabrica armas y armaduras con los materiales obtenidos en cada cacería.',
                'imagen' => '/imagenes/juegos/monster-hunter-world.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/582010/Monster_Hunter_World/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Monster Hunter Rise',
                'franquicia' => 'Monster Hunter',
                'anio' => 2021,
                'plataformas' => 'Nintendo Switch, PlayStation 4, PlayStation 5, Xbox One, Xbox Series X|S y PC',
                'genero' => 'Acción RPG y cacería',
                'desarrollador' => 'Capcom',
                'descripcion' => 'Defiende la aldea Kamura y domina nuevas formas de movimiento con el cordóptero mientras cazas monstruos solo o en equipo.',
                'imagen' => '/imagenes/juegos/monster-hunter-rise.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/1446780/MONSTER_HUNTER_RISE/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Monster Hunter Wilds',
                'franquicia' => 'Monster Hunter',
                'anio' => 2025,
                'plataformas' => 'PlayStation 5, Xbox Series X|S y PC',
                'genero' => 'Acción RPG y cacería',
                'desarrollador' => 'Capcom',
                'descripcion' => 'Viaja a las Tierras Prohibidas, donde el clima cambia los ecosistemas y altera el comportamiento de los monstruos y sus habitantes.',
                'imagen' => '/imagenes/juegos/monster-hunter-wilds.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/2246340/Monster_Hunter_Wilds/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Pokémon Esmeralda',
                'franquicia' => 'Pokémon',
                'anio' => 2004,
                'plataformas' => 'Game Boy Advance',
                'genero' => 'RPG y colección de criaturas',
                'desarrollador' => 'Game Freak',
                'descripcion' => 'Recorre la región de Hoenn, completa la Pokédex y enfrenta la amenaza simultánea del Equipo Magma y el Equipo Aqua.',
                'imagen' => '/imagenes/juegos/pokemon-esmeralda.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Pokémon Rojo Fuego',
                'franquicia' => 'Pokémon',
                'anio' => 2004,
                'plataformas' => 'Game Boy Advance y Nintendo Switch',
                'genero' => 'RPG y colección de criaturas',
                'desarrollador' => 'Game Freak',
                'descripcion' => 'Regresa a Kanto en esta nueva versión de Pokémon Rojo, captura criaturas, consigue ocho medallas y desafía al Alto Mando.',
                'imagen' => '/imagenes/juegos/pokemon-rojo-fuego.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://www.nintendo.com/us/store/products/spanish-pokemon-firered-version-switch/',
                'texto_enlace' => 'Ver en Nintendo',
            ],
            [
                'nombre' => 'Pokémon Escarlata',
                'franquicia' => 'Pokémon',
                'anio' => 2022,
                'plataformas' => 'Nintendo Switch',
                'genero' => 'RPG y mundo abierto',
                'desarrollador' => 'Game Freak',
                'descripcion' => 'Explora libremente la región de Paldea, completa tres grandes historias y descubre nuevos Pokémon junto a otros entrenadores.',
                'imagen' => '/imagenes/juegos/pokemon-escarlata.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://www.nintendo.com/us/store/products/pokemon-scarlet-switch/',
                'texto_enlace' => 'Ver en Nintendo',
            ],
            [
                'nombre' => 'Dragon Ball Z: Budokai Tenkaichi 3',
                'franquicia' => 'Dragon Ball',
                'anio' => 2007,
                'plataformas' => 'PlayStation 2 y Wii',
                'genero' => 'Lucha en 3D',
                'desarrollador' => 'Spike',
                'descripcion' => 'Combates tridimensionales con un amplio plantel de personajes, transformaciones, escenarios destructibles y ataques de las distintas sagas de Dragon Ball.',
                'imagen' => '/imagenes/juegos/dragon-ball-budokai-tenkaichi-3.jpg',
                'estado_disponibilidad' => 'Sin venta oficial',
                'enlace_oficial' => null,
                'texto_enlace' => null,
            ],
            [
                'nombre' => 'Dragon Ball Z: Kakarot',
                'franquicia' => 'Dragon Ball',
                'anio' => 2020,
                'plataformas' => 'PlayStation 4, PlayStation 5, Xbox One, Xbox Series X|S, Nintendo Switch y PC',
                'genero' => 'Acción RPG',
                'desarrollador' => 'CyberConnect2',
                'descripcion' => 'Revive la historia de Dragon Ball Z mediante combates, exploración, entrenamiento y actividades junto a sus personajes más conocidos.',
                'imagen' => '/imagenes/juegos/dragon-ball-z-kakarot.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/851850/DRAGON_BALL_Z_KAKAROT/',
                'texto_enlace' => 'Ver en Steam',
            ],
            [
                'nombre' => 'Dragon Ball: Sparking! ZERO',
                'franquicia' => 'Dragon Ball',
                'anio' => 2024,
                'plataformas' => 'PlayStation 5, Xbox Series X|S y PC',
                'genero' => 'Lucha en 3D',
                'desarrollador' => 'Spike Chunsoft',
                'descripcion' => 'La serie Budokai Tenkaichi regresa con combates de alta velocidad, transformaciones, ataques característicos y escenarios dinámicos.',
                'imagen' => '/imagenes/juegos/dragon-ball-sparking-zero.jpg',
                'estado_disponibilidad' => 'Disponible oficialmente',
                'enlace_oficial' => 'https://store.steampowered.com/app/1790600/DRAGON_BALL_Sparking_ZERO/',
                'texto_enlace' => 'Ver en Steam',
            ],
        ];

        foreach ($juegos as $juego) {
            Juego::updateOrCreate(
                ['nombre' => $juego['nombre']],
                $juego
            );
        }
    }
}
